### ISSUE TITLE
Do not override existing services

### ISSUE THREAD

**Issue by trasher** [leroy0211/Slim-Symfony-Dependency-Injection-Bridge#5]
Hi, 

With your current implementation, if services already exists in the container (say a router instance from a services.yml file for example) they'll be overrided since you do not check their presence.

This lends to get a working app, with a router instanciated; but twig views only access to another router instance, without any known route in my case.

**Comment by leroy0211** [comment]
I've tried to investigate it and it's not because I don't check their presence, but it's because Symfony doesn't allow to overwrite services. 

I'll have a new look into a fix for this.
