### ISSUE TITLE
Unable to dump the container

### ISSUE THREAD

**Issue by GMishx** [leroy0211/Slim-Symfony-Dependency-Injection-Bridge#6]
When trying to dump the resulting symfony container, I am getting following error:

```
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: Unable to dump a service container if a parameter is an object or a resource.
```

When I tried to dump the value which raises this error, I am getting this:

```
Slim\Http\Headers Object ( [data:protected] => Array ( [content-type] => Array ( [value] => Array ( [0] => text/html; charset=UTF-8 ) [originalKey] => Content-Type ) ) )
```

---

### Sample code

```php
$containerClassName = 'FossologyCachedContainer';
$container = new \Flexsounds\Component\SymfonyContainerSlimBridge\ContainerBuilder();

$container->setParameter('application_root', dirname(dirname(__DIR__)));
$loader = new \Symfony\Component\DependencyInjection\Loader\XmlFileLoader($container, new FileLocator(__DIR__));
$loader->load('services.xml');

$container->compile();
if ($cacheDir && is_dir($cacheDir))
{
  $dumper = new PhpDumper($container);
  umask(0027);
  file_put_contents(
    $cacheFile,
    $dumper->dump(array('class' => $containerClassName))
  );
}
```

**Comment by leroy0211** [comment]
I've fixed this in version 1.0.3. 

I've also started a new major version which I will pre-release soon. This contains the same setup, but with a different approach.

**Comment by GMishx** [comment]
Thanks for quick update. I'll check with 1.0.3 and get back to you.

**Comment by leroy0211** [comment]
> Thanks for quick update. I'll check with 1.0.3 and get back to you.

@GMishx I've also created a pre-release of version 2.0.0 (tagged 2.0.0-RC1). If you would like, you can try and test that version. Would be great to have some feedback about it!

The public interfaces should be the same, but it constructs the services a bit different.

**Comment by GMishx** [comment]
Hey, I tested my application with `1.0.3` and it worked perfectly for me. And for `2.0.0-rc1`, I would need some more time as my application still supports PHP 5.
